if(TARGET faset_ui AND TARGET faset_editor_session AND TARGET faset_scene_view)
    add_library(faset_editor_ui STATIC ${PROJECT_SOURCE_DIR}/src/editor/editor_ui.cpp)
    target_link_libraries(faset_editor_ui PUBLIC faset_ui faset_editor_session faset_scene_view)
    add_library(faset_project_launcher STATIC ${PROJECT_SOURCE_DIR}/apps/project_launcher.cpp)
    target_link_libraries(faset_project_launcher PUBLIC faset_ui faset_render)
    if(BUILD_TESTING)
        add_executable(faset_editor_project_settings_ui_tests ${PROJECT_SOURCE_DIR}/tests/editor_ui_project_settings.cpp)
        target_link_libraries(faset_editor_project_settings_ui_tests PRIVATE faset_editor_ui)
        target_compile_definitions(faset_editor_project_settings_ui_tests PRIVATE FASET_TEST_ENGINE="${PROJECT_SOURCE_DIR}")
        add_test(NAME editor_ui_project_settings COMMAND faset_editor_project_settings_ui_tests)
        set_tests_properties(editor_ui_project_settings PROPERTIES LABELS "gpu")
        add_executable(faset_editor_reload_ui_tests ${PROJECT_SOURCE_DIR}/tests/editor_ui_reload.cpp)
        target_link_libraries(faset_editor_reload_ui_tests PRIVATE faset_editor_ui)
        target_compile_definitions(faset_editor_reload_ui_tests PRIVATE FASET_TEST_ENGINE="${PROJECT_SOURCE_DIR}")
        add_test(NAME editor_ui_reload COMMAND faset_editor_reload_ui_tests)
        set_tests_properties(editor_ui_reload PROPERTIES LABELS "gpu")
        add_executable(faset_project_launcher_tests ${PROJECT_SOURCE_DIR}/tests/editor_ui_launcher.cpp)
        target_link_libraries(faset_project_launcher_tests PRIVATE faset_project_launcher)
        target_compile_definitions(faset_project_launcher_tests PRIVATE FASET_TEST_ENGINE="${PROJECT_SOURCE_DIR}")
        add_test(NAME editor_ui_launcher COMMAND faset_project_launcher_tests)
        set_tests_properties(editor_ui_launcher PROPERTIES LABELS "gpu")
        add_executable(faset_editor_ui_tests ${PROJECT_SOURCE_DIR}/tests/editor_ui_tests.cpp)
        target_link_libraries(faset_editor_ui_tests PRIVATE faset_editor_ui)
        target_compile_definitions(faset_editor_ui_tests PRIVATE FASET_TEST_ENGINE="${PROJECT_SOURCE_DIR}")
        if(TARGET faset_example_plugin)
            add_dependencies(faset_editor_ui_tests faset_example_plugin)
            target_compile_definitions(faset_editor_ui_tests PRIVATE FASET_TEST_PLUGIN_DIRECTORY="${PROJECT_BINARY_DIR}/example-plugin")
        endif()
        add_executable(faset_editor_template_ui_tests ${PROJECT_SOURCE_DIR}/tests/editor_ui_templates.cpp)
        target_link_libraries(faset_editor_template_ui_tests PRIVATE faset_editor_ui)
        target_compile_definitions(faset_editor_template_ui_tests PRIVATE FASET_TEST_ENGINE="${PROJECT_SOURCE_DIR}")
        add_test(NAME editor_ui_templates COMMAND faset_editor_template_ui_tests)
        set_tests_properties(editor_ui_templates PROPERTIES LABELS "gpu")
        add_executable(faset_editor_gizmo_ui_tests ${PROJECT_SOURCE_DIR}/tests/editor_ui_gizmos.cpp)
        target_link_libraries(faset_editor_gizmo_ui_tests PRIVATE faset_editor_ui)
        target_compile_definitions(faset_editor_gizmo_ui_tests PRIVATE FASET_TEST_ENGINE="${PROJECT_SOURCE_DIR}")
        add_test(NAME editor_ui_gizmos COMMAND faset_editor_gizmo_ui_tests)
        set_tests_properties(editor_ui_gizmos PROPERTIES LABELS "gpu")
        add_test(NAME editor_ui_authoring COMMAND faset_editor_ui_tests)
        set_tests_properties(editor_ui_authoring PROPERTIES LABELS "gpu")
    endif()
endif()
