if(TARGET faset_ui AND TARGET faset_editor_session AND TARGET faset_scene_view)
    add_library(faset_editor_ui STATIC ${PROJECT_SOURCE_DIR}/src/editor/editor_ui.cpp)
    target_link_libraries(faset_editor_ui PUBLIC faset_ui faset_editor_session faset_scene_view)
    if(BUILD_TESTING)
        add_executable(faset_editor_ui_tests ${PROJECT_SOURCE_DIR}/tests/editor_ui_tests.cpp)
        target_link_libraries(faset_editor_ui_tests PRIVATE faset_editor_ui)
        target_compile_definitions(faset_editor_ui_tests PRIVATE FASET_TEST_ENGINE="${PROJECT_SOURCE_DIR}")
        if(TARGET faset_example_plugin)
            add_dependencies(faset_editor_ui_tests faset_example_plugin)
            target_compile_definitions(faset_editor_ui_tests PRIVATE FASET_TEST_PLUGIN_DIRECTORY="${PROJECT_BINARY_DIR}/example-plugin")
        endif()
        add_test(NAME editor_ui_authoring COMMAND faset_editor_ui_tests)
        set_tests_properties(editor_ui_authoring PROPERTIES LABELS "gpu")
    endif()
endif()
